// Code generated by gonstructor --type=CryptocurrencyServiceImpl --constructorTypes=allArgs --output=./constructor.go; DO NOT EDIT.

package listing_service_impl

import (
	"github.com/vlad-golang/coinmarketcap-cli/internal/repo/point_repo_sql"
	go_coinmarketcap "github.com/vlad-golang/coinmarketcap-cli/pkg/go-coinmarketcap"
)

func NewCryptocurrencyServiceImpl(
	coinMarketCapClient *go_coinmarketcap.MarketCapClient,
	pointRepo *point_repo_sql.PointRepoSql,
) *CryptocurrencyServiceImpl {
	return &CryptocurrencyServiceImpl{
		coinMarketCapClient: coinMarketCapClient,
		pointRepo:           pointRepo,
	}
}
