// Code generated by gonstructor --type=PointRepoSql --constructorTypes=allArgs --output=./constructor.go; DO NOT EDIT.

package point_repo_sql

import "database/sql"

func NewPointRepoSql(db *sql.DB) *PointRepoSql {
	return &PointRepoSql{
		db: db,
	}
}
